import type { ExpoConfig } from "expo/config";
import { withGradleProperties, withAppBuildGradle } from "@expo/config-plugins";
import type { ConfigPlugin } from "@expo/config-plugins";

const bundleId = "com.app.voxclonemobile";
const scheme = "voxclone";

// sherpa-onnx (Qwen3/OmniVoice/Pocket engines) and onnxruntime-android
// (F5-TTS) both ship libonnxruntime.so — two full builds of the same runtime,
// so the native-lib merger keeps the first one. Without this pickFirst the
// release build dies on mergeReleaseNativeLibs with a duplicate-path error.
// The whole android/ directory is generated by `expo prebuild`, so hand-edited
// gradle.properties never survives CI: this plugin injects the pickFirst
// every time prebuild runs.
const withOnnxRuntimePickFirst: ConfigPlugin = (config) =>
  withGradleProperties(config, (props) => {
    const KEY = "android.packagingOptions.pickFirsts";
    const existing = props.modResults.find(
      (p): p is { type: "property"; key: string; value: string } =>
        p.type === "property" && p.key === KEY
    );
    if (existing) {
      existing.value = `${existing.value},**/libonnxruntime.so`;
    } else {
      props.modResults.push({
        type: "property",
        key: KEY,
        value: "**/libonnxruntime.so",
      });
    }
    return props;
  });

// The emulator only runs x86_64, real phones are arm64. A global `buildArchs`
// in expo-build-properties would force ONE ABI for every build type (and
// hand-edited android/ files never survive `expo prebuild` in CI), so the ABI
// set is injected per variant here: debug ships arm64 + x86_64, release stays
// arm64-only (leaner, faster installs).
const withPerVariantAbis: ConfigPlugin = (config) =>
  withAppBuildGradle(config, (props) => {
    let src = props.modResults.contents;
    const debugAnchor =
      /buildTypes \{\s*debug \{\s*signingConfig signingConfigs\.debug\s*\}/;
    const releaseAnchor = /release \{\n(\s*)\/\/ Caution!/;
    if (!src.includes('abiFilters "arm64-v8a", "x86_64"')) {
      src = src.replace(
        debugAnchor,
        `buildTypes {\n        debug {\n            signingConfig signingConfigs.debug\n            ndk {\n                abiFilters "arm64-v8a", "x86_64"\n            }\n        }`
      );
    }
    if (!src.includes('abiFilters "arm64-v8a"\n            }')) {
      src = src.replace(
        releaseAnchor,
        `release {\n            ndk {\n                abiFilters "arm64-v8a"\n            }\n$1// Caution!`
      );
    }
    props.modResults.contents = src;
    return props;
  });

const config: ExpoConfig = {
  name: "VoiceClone",
  slug: "vox-clone-mobile",
  version: "4.3.17",
  orientation: "portrait",
  icon: "./assets/images/icon.png",
  scheme: scheme,
  userInterfaceStyle: "automatic",
  newArchEnabled: true,
  ios: {
    supportsTablet: true,
    bundleIdentifier: bundleId,
    "infoPlist": {
        "ITSAppUsesNonExemptEncryption": false
      }
  },
  android: {
    versionCode: 20,
    adaptiveIcon: {
      backgroundColor: "#6366F1",
      foregroundImage: "./assets/images/android-icon-foreground.png",
      backgroundImage: "./assets/images/android-icon-background.png",
      monochromeImage: "./assets/images/android-icon-monochrome.png",
    },
    edgeToEdgeEnabled: true,
    predictiveBackGestureEnabled: false,
    package: bundleId,
    // REQUEST_INSTALL_PACKAGES (normal, non-runtime) : requis par l'installeur
    // Android pour installer un APK téléchargé (mise à jour depuis GitHub).
    permissions: ["POST_NOTIFICATIONS", "REQUEST_INSTALL_PACKAGES"],
    intentFilters: [
      {
        action: "VIEW",
        autoVerify: true,
        data: [
          {
            scheme: scheme,
            host: "*",
          },
        ],
        category: ["BROWSABLE", "DEFAULT"],
      },
    ],
  },
  web: {
    bundler: "metro",
    output: "static",
    favicon: "./assets/images/favicon.png",
  },
  plugins: [
    // This SDK's ExpoConfig type only lists string/tuple plugin entries, but
    // inline function plugins are supported at prebuild time — cast through
    // `unknown` to keep tsc happy.
    withOnnxRuntimePickFirst as unknown as string,
    withPerVariantAbis as unknown as string,
    "expo-router",
    [
      "expo-audio",
      {
        microphonePermission: "Allow $(PRODUCT_NAME) to access your microphone.",
      },
    ],
    [
      "expo-video",
      {
        supportsBackgroundPlayback: true,
        supportsPictureInPicture: true,
      },
    ],
    [
      "expo-splash-screen",
      {
        image: "./assets/images/splash-icon.png",
        imageWidth: 260,
        resizeMode: "contain",
        backgroundColor: "#6366F1",
        dark: {
          backgroundColor: "#6366F1",
        },
      },
    ],
    [
      "expo-build-properties",
      {
        android: {
          // reactNativeArchitectures drives the RN prebuilt libs at the
          // defaultConfig level (it is unioned/kept alongside the variant
          // abiFilters below, so release stays arm64-only while debug adds
          // x86_64 for the emulator).
          buildArchs: ["arm64-v8a"],
          minSdkVersion: 24,
          ndkVersion: "27.1.12297006",
        },
      },
    ],
  ],
  experiments: {
    typedRoutes: true,
    reactCompiler: true,
  },
};

export default config;
